### ISSUE TITLE
Doesn't work with svelte 3.5.1?

### ISSUE THREAD

**Issue by Meekohi** [rollup/rollup-plugin-svelte#59]
```
svelte: 3.5.1
rollup-plugin-svelte: 4.5.0
```

```
[!] Error: Cannot find module 'svelte/internal.js'
Error: Cannot find module 'svelte/internal.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at svelte (/Users/e/a/node_modules/rollup-plugin-svelte/index.js:129:32)
    at widgets.map.f (/Users/e/a/rollup.config.js:27:3)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/e/a/rollup.config.js:18:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..js (/Users/e/a/node_modules/rollup/bin/rollup:1270:24)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by Conduitry** [comment]
That's not the latest version of this plugin. If you're still seeing the issue with 5.0.3, please provide a complete reproduction.
